export const messageMap: Record<string, string> = {
  // Success messages
  "SUCCESS_SIGNED_UP": "Account created successfully 🎉",
  "SUCCESS_SIGNED_IN": "Logged in successfully 🎉",
  "SUCCESS_SIGN_OUT": "Signed out successfully",
  "SUCCESS_PASSWORD_RESET_EMAIL_SENT": "If an account exists with this email, a password reset link has been sent",
  "SUCCESS_PASSWORD_RESET": "Password reset successfully",
  "SUCCESS_VERIFY_EMAIL_SENT": "A verification email has been sent to your email address 📨",
  "SUCCESS_EMAIL_VERIFIED": "Email verified successfully 🎉",
  "SUCCESS_PROFILE_COMPLETED": "Profile completed successfully! 🎉",
  "SUCCESS_PROFILE_UPDATED": "Profile updated successfully ✨",
  "SUCCESS_LOCATION_UPDATED": "Location updated successfully 📍",
  "SUCCESS_UPDATE_USER_INTERESTS": "Interests updated successfully ✨",
  "SUCCESS_PHOTOS_UPLOADED": "Photos uploaded successfully 📸",
  "SUCCESS_PHOTOS_RETRIEVED": "Photos loaded successfully",
  "SUCCESS_PHOTO_DELETED": "Photo deleted successfully",
  "SUCCESS_PROFILE_PICTURE_SET": "Profile picture updated successfully ✨",
  "SUCCESS_GET_PUBLIC_PROFILE": "Profile loaded successfully",
  "SUCCESS_GET_PROFILE_VIEWS": "Profile views loaded successfully",
  "SUCCESS_CREATE_PROFILE_VIEW": "Profile view recorded",

  // Error messages
  "ERROR_ALREADY_LIKED_USER": "You have already liked this user",
  "ERROR_CANNOT_DELETE_LAST_PHOTO": "You must have at least one photo. Please upload a new photo before deleting this one",
  "ERROR_CANNOT_VIEW_OWN_PROFILE": "You cannot view your own profile this way. Use the profile page instead",
  "ERROR_EMAIL_ALREADY_EXISTS": "This email is already in use by another account. Please use a different email address",
  "ERROR_EMAIL_ALREADY_VERIFIED": "Email already verified. Please sign in",
  "ERROR_USERNAME_OR_EMAIL_ALREADY_EXISTS": "Username or email already exists. Please use a different one",
  "ERROR_FAILED_TO_RESOLVE_LOCATION": "Failed to resolve location. Please try again",
  "ERROR_FILE_TOO_LARGE": "File size exceeds the maximum limit of 5MB. Please choose a smaller image",
  "ERROR_FORBIDDEN": "You don't have permission to perform this action",
  "ERROR_IMAGE_TOO_SMALL": "Image is too small. Minimum dimensions are 200x200 pixels",
  "ERROR_INTERNAL_SERVER": "An unexpected internal server error occurred please try again later",
  "ERROR_INVALID_ASPECT_RATIO": "Image aspect ratio is too extreme. Please use a more standard image proportion",
  "ERROR_INVALID_COORDINATES": "Invalid coordinates provided",
  "ERROR_INVALID_CREDENTIALS": "Your username or password is incorrect. Please try again",
  "ERROR_INVALID_FILE_TYPE": "Invalid file type. Only JPEG and PNG images are allowed",
  "ERROR_INVALID_IMAGE": "Invalid or corrupted image file. Please upload a valid JPEG or PNG image",
  "ERROR_INVALID_INTEREST_IDS": "One or more interest IDs are invalid.",
  "ERROR_INVALID_LOCATION_TYPE": "Invalid location type provided",
  "ERROR_INVALID_OR_EXPIRED_RESET_TOKEN": "Invalid or expired reset password link. Please request a new one.",
  "ERROR_INVALID_OR_EXPIRED_VERIFY_EMAIL_TOKEN": "Invalid or expired email verification link. Please request a new one",
  "ERROR_INVALID_PASSWORD": "Password is not strong enough. Please use a stronger one",
  "ERROR_INVALID_REFRESH_TOKEN": "Invalid refresh token. Please sign in again",
  "ERROR_INVALID_TOKEN": "Invalid authentication token. Please sign in again",
  "ERROR_LOCATION_REQUIRED": "Location is required",
  "ERROR_MAX_PHOTOS_EXCEEDED": "You can upload a maximum of 6 photos. Please delete some photos before uploading new ones",
  "ERROR_MIME_MISMATCH": "File format mismatch detected. The file appears to be corrupted or not a valid image",
  "ERROR_MISSING_PARAMETER": "Required parameter is missing",
  "ERROR_MISSING_PARAMETERS": "Required parameters are missing",
  "ERROR_NO_FILES": "No files provided. Please select at least one photo to upload",
  "ERROR_NO_PHOTOS": "You must upload at least one photo before completing your profile",
  "ERROR_NO_PROFILE_PICTURE": "You must select a profile picture",
  "ERROR_NO_REFRESH_TOKEN_PROVIDED": "No refresh token provided. Please sign in again",
  "ERROR_NO_TOKEN_PROVIDED": "No authentication token provided. Please sign in",
  "ERROR_NO_UPDATE_FIELDS": "No fields provided for update.",
  "ERROR_NOT_FOUND": "Resource not found",
  "ERROR_NOT_LIKED_USER": "You have not liked this user",
  "ERROR_NOTIFICATION_TYPE_NOT_FOUND": "Notification type not found",
  "ERROR_NOTIFICATION_USER_NOT_FOUND": "Notification user not found",
  "ERROR_PHOTO_CREATION_FAILED": "Failed to create photo. Please try again",
  "ERROR_PHOTO_NOT_FOUND": "Photo not found. It may have been already deleted",
  "ERROR_PHOTO_UPLOAD_FAILED": "Photo upload failed. Please try again later",
  "ERROR_PROFILE_ALREADY_COMPLETED": "Profile is already completed",
  "ERROR_PROFILE_PIC_EXISTS": "A profile picture is already set for this user",
  "ERROR_REFRESH_TOKEN_EXPIRED": "Refresh token has expired. Please sign in again",
  "ERROR_SELF_BLOCK_NOT_ALLOWED": "You cannot block yourself",
  "ERROR_SELF_LIKE_NOT_ALLOWED": "You cannot like yourself",
  "ERROR_SELF_REPORT_NOT_ALLOWED": "You cannot report yourself",
  "ERROR_SELF_UNBLOCK_NOT_ALLOWED": "You cannot unblock yourself",
  "ERROR_SELF_UNLIKE_NOT_ALLOWED": "You cannot unlike yourself",
  "ERROR_TOKEN_AND_NEW_PASSWORD_REQUIRED": "Token and new password are required",
  "ERROR_UNKNOWN": "An unknown error occurred. Please try again.",
  "ERROR_USER_LOCATION_NOT_SET": "User location is not set",
  "ERROR_USER_NOT_BLOCKED": "User is not blocked",
  "ERROR_USER_NOT_FOUND": "User not found",
  "ERROR_VALIDATION_FAILED": "The data you provided is invalid. Please check your inputs and try again.",
}

export const getToastMessage = (key: string, errorDetails?: string) => {
  if (key === 'ERROR_VALIDATION_FAILED' && errorDetails) {
    return errorDetails;
  }
  return messageMap[key] || messageMap['ERROR_UNKNOWN'];
}